spring:
  application:
    name: scholar-ai
  security:
    user:
      name: ${USER_NAME:your_username_here}
      password: ${USER_PASSWORD:your_password_here}
  app:
    jwtSecret: ${JWT_SECRET:your_jwt_secret_here}
    jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}

  datasource:
    url: jdbc:postgresql://localhost:5433/coreDB
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        hbm2ddl.auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
      base-path: "/actuator"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: "${spring.application.name}"
  tracing:
    enabled: false
    sampling:
      probability: 1

springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  use-management-port: false
  swagger-ui:
    path: /docs

resilience4j:
  ratelimiter:
    configs:
      default:
        limit-for-period: 300
        limit-refresh-period: 1m
        timeout-duration: 0s
    instances:
      standard-api:
        base-config: default
      test-error:
        limit-for-period: 30
        limit-refresh-period: 10s
        timeout-duration: 0s
      actuator:
        limit-for-period: 60
        limit-refresh-period: 1m
        timeout-duration: 0s

scholarai:
  rabbitmq:
    exchange: scholarai.exchange
    paper-fetch:
      queue: scholarai.paper.fetch.queue
      routing-key: scholarai.paper.fetch
      completed-queue: scholarai.paper.fetch.completed.queue
      completed-routing-key: scholarai.paper.fetch.completed
    web-search:
      queue: scholarai.websearch.queue
      routing-key: scholarai.websearch
      completed-queue: scholarai.websearch.completed.queue
      completed-routing-key: scholarai.websearch.completed
    summarization:
      queue: scholarai.summarization.queue
      routing-key: scholarai.summarization
      completed-queue: scholarai.summarization.completed.queue
      completed-routing-key: scholarai.summarization.completed
    gap-analysis:
      queue: scholarai.gap.queue
      routing-key: scholarai.gap
      completed-queue: scholarai.gap.completed.queue
      completed-routing-key: scholarai.gap.completed

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://scholarAI.tech,https://*.vercel.app}