services:
  core-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        ENV: ${ENV}
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped
    networks:
      - scholar_network_alias
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV}

networks:
  scholar_network_alias:
    name: docker_scholar-network
    external: true        


