version: "3.8"

services:
  core:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        ENV: dev
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M     # Limit usage to 512MB
        reservations:
          memory: 256M     # Minimum guaranteed 256MB
    restart: unless-stopped
    networks:
      - monitoring-network
    env_file:
      - .env
    environment:
       - SPRING_PROFILES_ACTIVE=dev

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "16379:6379"
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge
