services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - ENV=dev
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped
    networks:
      - monitoring-network
    env_file:
      - ../.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev

networks:
  monitoring-network:
    driver: bridge
